# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: playwright-tests
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: playwright-tests
#   template:
#     metadata:
#       labels:
#         app: playwright-tests
#     spec:
#       containers:
#         - name: playwright
#           image: jack2153/pw-1  # Ensure this image exists in the registry or Minikube's local Docker
#           imagePullPolicy: IfNotPresent
#           command: ["npx", "playwright", "test","example.spec.js"]
#           workingDir: /app  # Optional: Specify if your Playwright tests are inside a specific directory
#           resources:
#             limits:
#               memory: "3Gi"
#               cpu: "1"
#             requests:
#               memory: "1Gi"
#               cpu: "750m"
        
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: playwright-tests
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: playwright-tests
#   template:
#     metadata:
#       labels:
#         app: playwright-tests
#     spec:
#       volumes:
#         - name: test-results
#           persistentVolumeClaim:
#             claimName: test-results-pvc
#         - name: shared-data
#           persistentVolumeClaim:
#             claimName: playwright-pvc
#       containers:
#         - name: playwright-1
#           image: jack2153/playwright-tests-1:latest
#           imagePullPolicy: IfNotPresent
#           command: ["/bin/sh", "-c"]
#           args: ["npx playwright test example.spec.js"]
#           workingDir: /app
#           volumeMounts:
#             - name: test-results
#               mountPath: /app/test-results
#             - name: shared-data
#               mountPath: /app/shared
#           resources:
#             limits:
#               memory: "1Gi"
#               cpu: "1"
#             requests:
#               memory: "500Mi"
#               cpu: "250m"
#         - name: playwright-2
#           image: jack2153/playwright-tests-1:latest
#           imagePullPolicy: IfNotPresent
#           command: ["/bin/sh", "-c"]
#           args: ["npx playwright test example2.spec.js"]
#           workingDir: /app
#           volumeMounts:
#             - name: test-results
#               mountPath: /app/test-results
#             - name: shared-data
#               mountPath: /app/shared
#           resources:
#             limits:
#               memory: "1Gi"
#               cpu: "1"
#             requests:
#               memory: "500Mi"
#               cpu: "250m"
#         - name: playwright-3
#           image: jack2153/playwright-tests-1:latest
#           imagePullPolicy: IfNotPresent
#           command: ["/bin/sh", "-c"]
#           args: ["npx playwright test example3.spec.js"]
#           workingDir: /app
          # volumeMounts:
          #   - name: test-results
          #     mountPath: /app/test-results
          #   - name: shared-data
          #     mountPath: /app/shared
#           resources:
#             limits:
#               memory: "1Gi"
#               cpu: "1"
#             requests:
#               memory: "500Mi"
#               cpu: "250m"

# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: playwright-tests
# spec:
#   parallelism: 10
#   completions: 10
#   template:
#     metadata:
#       labels:
#         app: playwright-tests
#       annotations:
#         batch.kubernetes.io/job-completion-index: "0" # Default (will be overridden by Kubernetes)
#     spec:
#       restartPolicy: Never
#       containers:
#         - name: playwright
#           image: jack2153/pw-3:latest
#           imagePullPolicy: Always
#           env:
#             - name: JOB_COMPLETION_INDEX
#               valueFrom:
#                 fieldRef:
#                   fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
#           command: ["/bin/sh", "-c"]
#           args:
#             - |
#               echo "Pod completion index: $JOB_COMPLETION_INDEX"
#               test_file="/app/tests/example$((JOB_COMPLETION_INDEX + 1)).spec.js"
#               echo "Running test: $test_file"
#               if [ -f "$test_file" ]; then
#                 npx playwright test "$test_file"
#               else
#                 echo "Error: $test_file not found!"
#                 exit 1
#               fi
#           workingDir: /app  # Ensure the correct working directory
#           resources:
#             requests:
#               memory: "750Mi"  # Request 750MB RAM
#               cpu: "300m"  # Request 0.25 CPU core
#             limits:
#               memory: "1Gi"  # Set max 1GB RAM
#               cpu: "1"  

---
apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test-1
spec:
  template:
    metadata:
      labels:
        app: playwright-test-1
    spec:
      volumes:
        - name: test-results
          persistentVolumeClaim:
            claimName: test-results-pvc
        - name: shared-data
          persistentVolumeClaim:
            claimName: playwright-pvc
      restartPolicy: Never
      containers:
        - name: playwright
          image: jack2153/pw-3:latest
          command: ["/bin/sh", "-c"]
          args: ["npx playwright test /app/tests/example1.spec.js"]
          volumeMounts:
            - name: test-results
              mountPath: /app/test-results
            - name: shared-data
              mountPath: /app/shared
---
apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test-2
spec:
  template:
    metadata:
      labels:
        app: playwright-test-2
    spec:
      volumes:
        - name: test-results
          persistentVolumeClaim:
            claimName: test-results-pvc
        - name: shared-data
          persistentVolumeClaim:
            claimName: playwright-pvc
      restartPolicy: Never
      containers:
        - name: playwright
          image: jack2153/pw-3:latest
          command: ["/bin/sh", "-c"]
          args: ["npx playwright test /app/tests/example2.spec.js"]
          volumeMounts:
            - name: test-results
              mountPath: /app/test-results
            - name: shared-data
              mountPath: /app/shared
---
apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test-3
spec:
  template:
    metadata:
      labels:
        app: playwright-test-3
    spec:
      volumes:
        - name: test-results
          persistentVolumeClaim:
            claimName: test-results-pvc
        - name: shared-data
          persistentVolumeClaim:
            claimName: playwright-pvc
      restartPolicy: Never
      containers:
        - name: playwright
          image: jack2153/pw-3:latest
          command: ["/bin/sh", "-c"]
          args: ["npx playwright test /app/tests/example3.spec.js"]
          volumeMounts:
            - name: test-results
              mountPath: /app/test-results
            - name: shared-data
              mountPath: /app/shared
---
apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test-4
spec:
  template:
    metadata:
      labels:
        app: playwright-test-4
    spec:
      volumes:
        - name: test-results
          persistentVolumeClaim:
            claimName: test-results-pvc
        - name: shared-data
          persistentVolumeClaim:
            claimName: playwright-pvc
      restartPolicy: Never
      containers:
        - name: playwright
          image: jack2153/pw-3:latest
          command: ["/bin/sh", "-c"]
          args: ["npx playwright test /app/tests/example4.spec.js"]
          volumeMounts:
            - name: test-results
              mountPath: /app/test-results
            - name: shared-data
              mountPath: /app/shared
---
apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test-5
spec:
  template:
    metadata:
      labels:
        app: playwright-test-5
    spec:
      volumes:
        - name: test-results
          persistentVolumeClaim:
            claimName: test-results-pvc
        - name: shared-data
          persistentVolumeClaim:
            claimName: playwright-pvc
      restartPolicy: Never
      containers:
        - name: playwright
          image: jack2153/pw-3:latest
          command: ["/bin/sh", "-c"]
          args: ["npx playwright test /app/tests/example5.spec.js"]
          volumeMounts:
            - name: test-results
              mountPath: /app/test-results
            - name: shared-data
              mountPath: /app/shared
---
apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test-6
spec:
  template:
    metadata:
      labels:
        app: playwright-test-6
    spec:
      volumes:
        - name: test-results
          persistentVolumeClaim:
            claimName: test-results-pvc
        - name: shared-data
          persistentVolumeClaim:
            claimName: playwright-pvc
      restartPolicy: Never
      containers:
        - name: playwright
          image: jack2153/pw-3:latest
          command: ["/bin/sh", "-c"]
          args: ["npx playwright test /app/tests/example6.spec.js"]
          volumeMounts:
            - name: test-results
              mountPath: /app/test-results
            - name: shared-data
              mountPath: /app/shared
---
apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test-7
spec:
  template:
    metadata:
      labels:
        app: playwright-test-7
    spec:
      volumes:
        - name: test-results
          persistentVolumeClaim:
            claimName: test-results-pvc
        - name: shared-data
          persistentVolumeClaim:
            claimName: playwright-pvc
      restartPolicy: Never
      containers:
        - name: playwright
          image: jack2153/pw-3:latest
          command: ["/bin/sh", "-c"]
          args: ["npx playwright test /app/tests/example7.spec.js"]
          volumeMounts:
            - name: test-results
              mountPath: /app/test-results
            - name: shared-data
              mountPath: /app/shared
---
apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test-8
spec:
  template:
    metadata:
      labels:
        app: playwright-test-8
    spec:
      volumes:
        - name: test-results
          persistentVolumeClaim:
            claimName: test-results-pvc
        - name: shared-data
          persistentVolumeClaim:
            claimName: playwright-pvc
      restartPolicy: Never
      containers:
        - name: playwright
          image: jack2153/pw-3:latest
          command: ["/bin/sh", "-c"]
          args: ["npx playwright test /app/tests/example8.spec.js"]
          volumeMounts:
            - name: test-results
              mountPath: /app/test-results
            - name: shared-data
              mountPath: /app/shared
---
apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test-9
spec:
  template:
    metadata:
      labels:
        app: playwright-test-9
    spec:
      volumes:
        - name: test-results
          persistentVolumeClaim:
            claimName: test-results-pvc
        - name: shared-data
          persistentVolumeClaim:
            claimName: playwright-pvc
      restartPolicy: Never
      containers:
        - name: playwright
          image: jack2153/pw-3:latest
          command: ["/bin/sh", "-c"]
          args: ["npx playwright test /app/tests/example9.spec.js"]
          volumeMounts:
            - name: test-results
              mountPath: /app/test-results
            - name: shared-data
              mountPath: /app/shared
---
apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test-10
spec:
  template:
    metadata:
      labels:
        app: playwright-test-10
    spec:
      volumes:
        - name: test-results
          persistentVolumeClaim:
            claimName: test-results-pvc
        - name: shared-data
          persistentVolumeClaim:
            claimName: playwright-pvc
      restartPolicy: Never
      containers:
        - name: playwright
          image: jack2153/pw-3:latest
          command: ["/bin/sh", "-c"]
          args: ["npx playwright test /app/tests/example10.spec.js"]
          volumeMounts:
            - name: test-results
              mountPath: /app/test-results
            - name: shared-data
              mountPath: /app/shared
---
apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test-11
spec:
  template:
    metadata:
      labels:
        app: playwright-test-11
    spec:
      volumes:
        - name: test-results
          persistentVolumeClaim:
            claimName: test-results-pvc
        - name: shared-data
          persistentVolumeClaim:
            claimName: playwright-pvc
      restartPolicy: Never
      containers:
        - name: playwright
          image: jack2153/pw-3:latest
          command: ["/bin/sh", "-c"]
          args: ["npx playwright test /app/tests/example11.spec.js"]
          volumeMounts:
            - name: test-results
              mountPath: /app/test-results
            - name: shared-data
              mountPath: /app/shared
---
apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-test-12
spec:
  template:
    metadata:
      labels:
        app: playwright-test-12
    spec:
      volumes:
        - name: test-results
          persistentVolumeClaim:
            claimName: test-results-pvc
        - name: shared-data
          persistentVolumeClaim:
            claimName: playwright-pvc
      restartPolicy: Never
      containers:
        - name: playwright
          image: jack2153/pw-3:latest
          command: ["/bin/sh", "-c"]
          args: ["npx playwright test /app/tests/example12.spec.js"]
          volumeMounts:
            - name: test-results
              mountPath: /app/test-results
            - name: shared-data
              mountPath: /app/shared