apiVersion: apps/v1
kind: Deployment
metadata:
  name: playwright-tests
spec:
  replicas: 10
  selector:
    matchLabels:
      app: playwright-tests
  template:
    metadata:
      labels:
        app: playwright-tests
    spec:
      containers:
        - name: playwright
          image: jack2153/playwright-tests-1  # Ensure this image exists in the registry or Minikube's local Docker
          imagePullPolicy: IfNotPresent
          command: ["npx", "playwright", "test"]
          workingDir: /app  # Optional: Specify if your Playwright tests are inside a specific directory
          resources:
            limits:
              memory: "3Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "500m"
