apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playwright-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Adjust based on your needs
  storageClassName: standard  # Ensure this matches your cluster's StorageClass
