./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-1 --work ./_work1
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-2 --work ./_work2
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-3 --work ./_work3
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-4 --work ./_work4
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-5 --work ./_work5
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-6 --work ./_work6
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-7 --work ./_work7
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-8 --work ./_work8
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-9 --work ./_work9
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-10 --work ./_work10
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-11 --work ./_work11
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-12 --work ./_work12
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-13 --work ./_work13
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-14 --work ./_work14
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-15 --work ./_work15
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-16 --work ./_work16
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-17 --work ./_work17
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-18 --work ./_work18
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-19 --work ./_work19
./config.sh --url https://github.com/Jayspatel21/playwrightb --token A556VQSJMMXKVAAVKCIANILHUCRM2 --name runner-20 --work ./_work20
