name: Docker CI/CD

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}

        # - name: Build and push Docker image
        #   uses: docker/build-push-action@v4
        #   with:
        #         context: .
        #         push: true
        #         tags: |
        #             jack2153/playwright-tests-1:latest
        #             jack2153/playwright-tests-1:latest
        #         cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/playwrightb:buildcache
        #         cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/playwrightb:buildcache,mode=max

        - name: Run Docker container
          run: |
                docker pull jack2153/playwright-tests-1:latest
                docker run jack2153/playwright-tests-1:latest